# Generated by Django 4.2.20 on 2025-04-10 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kyberapp', '0004_test_usertest_testresult_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='achievement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kyberapp.achievement'),
        ),
    ]
