# Generated by Django 4.2.20 on 2025-04-10 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyberapp', '0005_task_achievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='task',
            name='hint',
        ),
    ]
